### ISSUE TITLE
Installing iOS Mapbox Navigation in Xcode 8

### ISSUE THREAD

**Issue by josephdhooper** [mapbox/mapbox-navigation-ios#253]
After trying to install Mapbox Navigation using Carthage, the following errors keep appearing: 

 > include of non-modular header inside framework module 'MapboxNavigation.MGLMapView_MGLNavigationAdditions': '/Users/user/Downloads/mapbox-navigation-ios-0.3.0/Carthage/Build/iOS/Mapbox.framework/Headers/Mapbox.h'

and

 > could not build Objective-C module 'MapboxNavigation'

I've tried to change the `Allow Non-modular Includes in Framework Modules` to `yes` and change Headers to `project` as indicated [here][1]. All to no avail. 

The other option was to try CocoaPods. However, I keep getting the following error: 

> No such module 'MapboxDirections'

I'm using the MapboxNavigation.xcworkspace file and using the Example-Swift schema. 

Can't find a solution. 

  [1]: https://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module

**Comment by frederoni** [comment]
The xcworkspace file could be leftover from when we used CocoaPods but we moved to Carthage.
Run `carthage update --platform ios --cache-builds` and open MapboxNavigation.xcodeproj to try out the examples.

**Comment by josephdhooper** [comment]
Hi! I've tried to use Carthage to run the examples as you suggested, but I'm still getting the same errors: 

- include of non-modular header inside framework module 'MapboxNavigation.MGLMapView_MGLNavigationAdditions': '/Users/user/Downloads/mapbox-navigation-ios-0.3.0/Carthage/Build/iOS/Mapbox.framework/Headers/Mapbox.h'

- could not build Objective-C module 'MapboxNavigation'

**Comment by frederoni** [comment]
What version of Carthage and Xcode are you using? Can you download the library again without changing any build settings? It should build right out of the box. The fact that you have a .xcworkspace-file indicates that you have an old version and tried CocoaPods but I assume you downloaded the 0.3 release which the name of the directory indicates?

**Comment by josephdhooper** [comment]
I'm running Carthage version 0.23.0. I removed the library and downloaded it again. After trying to build the Swift example without changing anything, I get the following error: 

- No such module 'Mapbox Directions'

**Comment by frederoni** [comment]
We just released version 0.4.0. Would you mind giving it another try?

**Comment by josephdhooper** [comment]
Tried again with the newly released version but still getting the same compile errors: 

> include of non-modular header inside framework module 'MapboxNavigation.MGLMapView_MGLNavigationAdditions': '/Users/johooper/Downloads/mapbox-navigation-ios-0.4.0/Carthage/Build/iOS/Mapbox.framework/Headers/Mapbox.h'

> could not build Objective-C module 'MapboxNavigation'

**Comment by jmkiley** [comment]
Hi @josephdhooper!

Could you check if you are installing the Mapbox iOS SDK in addition to the Mapbox Navigation SDK (which also has the Mapbox iOS SDK as a dependency)? One cause of this issue is when the Mapbox iOS SDK is being installed twice.

**Comment by josephdhooper** [comment]
Yes, the issue persists. When building the sample project using Carthage, I noticed that the `binary-only framework Mapbox-iOS-SDK` is downloaded and the `mapbox.framework` is included in the framework folder.

**Comment by josephdhooper** [comment]
And, when creating a new project using cocoa pods, I noticed that the `Mapbox-iOS-SDK` is downloaded and the `Mapbox-iOS-SDK` is included within the `Pods` folder.

**Comment by NarendraInexture** [comment]
@josephdhooper  have you solved this error. @jmkiley  @frederoni  i am facing same issue.
My carthage version is 0.23.0. just clone the project and run 
![screen shot 2017-06-16 at 5 46 45 pm](https://user-images.githubusercontent.com/29482904/27226283-d6cf9df6-52bb-11e7-8772-a752fb408a0d.png)

I have attched the screenshot please check it and tell me where i am wrong.

**Comment by josephdhooper** [comment]
Unfortunately, I have not solved the issue.

**Comment by frederoni** [comment]
@madBureaToT Can you include the output from the log? (Please check the xcodebuild log for more details) Preferably in a gist and ref that here.

**Comment by madBureaToT** [comment]
i have just written `pod 'MapboxNavigation', '~> 0.4.0'` for my new project of navigation mapBox. it installed well, doesn't throw any error. but when i run the code without inserting any snippets. it give this error.

Command failed due to signal fault 11.  

here is my log file for that issue.

**CompileSwift normal x86_64 /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteLeg.swift
    cd /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods
    "/Applications/Xcode 8.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift" -frontend -c /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBAttribute.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBDirections.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBIntersection.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBLane.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBLaneIndication.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRoute.swift -primary-file /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteLeg.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteOptions.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteStep.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBWaypoint.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk "/Applications/Xcode 8.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk" -I /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift -F /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift -F /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/Polyline -enable-testing -g -import-underlying-module -module-cache-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-generated-files.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-own-target-headers.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-project-headers.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift/include -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Private -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Public -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Public/Mapbox-iOS-SDK -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/DerivedSources/x86_64 -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods -emit-module-doc-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg~partial.swiftdoc -Onone -module-name MapboxDirections -emit-module-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg~partial.swiftmodule -serialize-diagnostics-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.dia -emit-dependencies-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.d -emit-reference-dependencies-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.swiftdeps -o /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.o

0  swift                    0x00000001050c1b6d PrintStackTraceSignalHandler(void*) + 45
1  swift                    0x00000001050c15b6 SignalHandler(int) + 470
2  libsystem_platform.dylib 0x00007fff8985952a _sigtramp + 26
3  libsystem_platform.dylib 0x00007fff5d797ce4 _sigtramp + 3555977172
4  swift                    0x00000001025dcfec void llvm::function_ref<void (swift::irgen::GenericRequirement)>::callback_fn<(anonymous namespace)::EmitPolymorphicArguments::emit(swift::CanTypeWrapper<swift::SILFunctionType>, llvm::ArrayRef<swift::Substitution>, swift::irgen::WitnessMetadata*, swift::irgen::Explosion&)::$_14>(long, swift::irgen::GenericRequirement) + 716
5  swift                    0x00000001025d29e1 (anonymous namespace)::PolymorphicConvention::enumerateRequirements(llvm::function_ref<void (swift::irgen::GenericRequirement)> const&) + 129
6  swift                    0x00000001025dcbdb swift::irgen::emitPolymorphicArguments(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::SILFunctionType>, swift::CanTypeWrapper<swift::SILFunctionType>, llvm::ArrayRef<swift::Substitution>, swift::irgen::WitnessMetadata*, swift::irgen::Explosion&) + 459
7  swift                    0x00000001026394f5 (anonymous namespace)::IRGenSILFunction::visitFullApplySite(swift::FullApplySite) + 2997
8  swift                    0x0000000102624268 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 9080
9  swift                    0x0000000102548601 swift::irgen::IRGenerator::emitGlobalTopLevel() + 1329
10 swift                    0x0000000102609fcb performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, unsigned int) + 1259
11 swift                    0x00000001024d81c7 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*) + 23687
12 swift                    0x00000001024d0265 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 17029
13 swift                    0x000000010248d82d main + 8685
14 libdyld.dylib            0x00007fff8abd25ad start + 1
Stack dump:
0.	Program arguments: /Applications/Xcode 8.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBAttribute.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBDirections.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBIntersection.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBLane.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBLaneIndication.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRoute.swift -primary-file /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteLeg.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteOptions.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteStep.swift /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBWaypoint.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode 8.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -I /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift -F /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift -F /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/Polyline -enable-testing -g -import-underlying-module -module-cache-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-generated-files.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-own-target-headers.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/MapboxDirections-project-headers.hmap -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Products/Debug-iphonesimulator/MapboxDirections.swift/include -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Private -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Public -Xcc -I/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/Headers/Public/Mapbox-iOS-SDK -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/DerivedSources/x86_64 -Xcc -I/Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods -emit-module-doc-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg~partial.swiftdoc -Onone -module-name MapboxDirections -emit-module-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg~partial.swiftmodule -serialize-diagnostics-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.dia -emit-dependencies-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.d -emit-reference-dependencies-path /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.swiftdeps -o /Users/lokeshdudhat/Library/Developer/Xcode/DerivedData/mapBoxDemo-csvpfecdeexsjmfhvkibaawesybw/Build/Intermediates/Pods.build/Debug-iphonesimulator/MapboxDirections.swift.build/Objects-normal/x86_64/MBRouteLeg.o 
1.	While emitting IR SIL function @_TFC16MapboxDirections8RouteLeg6encodefT4withCSo7NSCoder_T_ for 'encode' at /Users/lokeshdudhat/Desktop/Project/mapBoxDemo/Pods/MapboxDirections.swift/MapboxDirections/MBRouteLeg.swift:98:12**

**Comment by frederoni** [comment]
> i have just written pod 'MapboxNavigation', '~> 0.4.0' for my new project of navigation mapBox. it installed well, doesn't throw any error. but when i run the code without inserting any snippets.

What do you mean by "run the code without inserting any snippets"?

**Comment by frederoni** [comment]
The file path of your toolchain indicates you are using an outdated version of Xcode.
What does `xcode-select -p` output?

**Comment by madBureaToT** [comment]
`xcode-select -p `

 output is 

**/Applications/Xcode 2.app/Contents/Developer**

**run the code without inserting any snippets"** it's means just install framework and try to build without writting a single code.

**Comment by frederoni** [comment]
Ok, please try installing through the App Store. I think there are a couple of Swift 3 features in MapboxDirections and Carthage that requires Xcode 8.3.

**Comment by madBureaToT** [comment]
@frederoni  Again Same issue are there. I just installed latest version of xcode that is 8.3.2
followed the same procedure, but haven't get the solution.

One thing i noticed when i installed using pods and build the code.

it give me this error. **command failed due to segmantation fault 11** This error is in `routeLeg.swift`. 

and when i just try to run code through clone/download he project and update carthage by using this command  `carthage update --platform ios ` it gives the same error that is **No such module mapbox direction** and i don't think it's problem of xcode version. please check this and let me know if there is any solution for that.

**Comment by frederoni** [comment]
@madBureaToT Sorry about the delay here.

What does `xcode-select -p` output after you've installed Xcode through the App Store?
You might have to `sudo xcode-select -s /Applications/Xcode.app/` if it's using a different toolchain.

**Comment by madBureaToT** [comment]
output of `xcode-select -p` after installation

**/Applications/Xcode.app/Contents/Developer**

**Comment by chriszhang4213** [comment]
I have same issue like this, it always show could not build module either in Mapboxdirection or this this one. sometimes when I clean the device data then rebuild, it will disappear.but after I change to another device or after certain amount of time, it shows again. anyone knows how to fix this now?

**Comment by chriszhang4213** [comment]
it seems like the error message is showing  but i am still able to run my app. this is so confused.

**Comment by minikarma** [comment]
tha same issue

`xcode-select -p` */Applications/Xcode.app/Contents/Developer*
having XCode installed via AppStore recently

**Comment by frederoni** [comment]
Any updates here @josephdhooper? Can we close this issue?

**Comment by josephdhooper** [comment]
I recently tried to build the example using Carthage but I still get the same errors that I described above. I'm not sure what else to try. Any help would be greatly appreciated.

**Comment by josephdhooper** [comment]
I also tried to install with cocoapods into a live app that uses Mapbox Directions, and I received the same error as describe above.

**Comment by doriansgithub** [comment]
So Mabbox doesn't support Pod any longer?

**Comment by bsudekum** [comment]
@doriansgithub we do support both pods and carthage. Can you give v0.10.0 a try and let me know how it goes?

**Comment by doriansgithub** [comment]
Ok, will do.  I have another question.  What is the cost to my clients for downloading a city?

**Comment by doriansgithub** [comment]
Also, now we cannot have Mapbox’s pod on git because it’s over 100MB.  We’ve had to make changes so that everyone has their pods locally, but that’s not a very efficient way of working.

Can’t the pod be divided into parts that are under 100MB?

**Comment by bsudekum** [comment]
@doriansgithub is it necessary to check in all dependencies? For projects at Mapbox, we ignore the pods folder and rely on the `Podfile` to download all necessary dependencies. 

> I have another question.  What is the cost to my clients for downloading a city?

Can you please contact support@mapbox.com for this question?

**Comment by bsudekum** [comment]
Also noting that this project now requires Xcode 9 and will require Swift 4 when v0.11.0 is released. There is a release candidate out now if you'd like to test it: `v0.11.0-rc.1`.

**Comment by doriansgithub** [comment]
Got it.  Yes, we are moving to swift 4.

Thanks!

**Comment by doriansgithub** [comment]
agreed.

Thanks

**Comment by doriansgithub** [comment]
Question:  Can Mapbox be used as an overlay like OpenStreetMap?

**Comment by bsudekum** [comment]
@doriansgithub Would you opening a separate ticket with your question? This may also be a better question to ask `support@mapbox.com` since it may not have to do with the Navigation SDK.

**Comment by doriansgithub** [comment]
ok, will do.

**Comment by Nirajpaul2** [comment]
Hi friend , we have problem to install pod , we using the xcode 8.3.1 . i am going step by step.

1. we have no problem to install MapBox framework for the simple map implementation.
2. we have problem to install **pod MapboxNavigation', '~> 0.16** . i am follow the [Step here](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.16.2/) 

3. what is inside me pod ,see below

> target 'MapBoxDemo' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> pod 'MapboxNavigation'
> end

4. when i am going to install pod the [issues appear ](https://stackoverflow.com/questions/50063034/mapbox-pod-installation-failure)
